config/routes.rb
Rails.application.routes.draw do
  resources :entries
  root to:"entries#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy!

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<% content_for :title do %>
    <%= @entry.meal_type %> &ndash; <%= DateTime.now.strftime("%B %e, %Y") %>
<% end %>

    <nav class="panel is-link">
      <p class="panel-heading">
        <%= @entry.meal_type %>
      </p>
      <div class="panel-block">
        Calories :<%= entry.calories %>
      </div>
      <div class="panel-block">
        Proteins :<%= entry.proteins %>
      </div>
      <div class="panel-block">
        Carbohydrates :<%= entry.carbohydrates %>
      </div>
      <div class="panel-block">
        Fats :<%= entry.fats %>
      </div>
    </nav>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meal_type, class: "label" %>
    <%= form.text_field :meal_type, class: "input" %>
  </div>

  <div>
    <%= form.label :calories, class: "label" %>
    <%= form.number_field :calories, class: "input" %>
  </div>

  <div>
    <%= form.label :proteins, class: "label" %>
    <%= form.number_field :proteins, class: "input" %>
  </div>

  <div>
    <%= form.label :carbohydrates, class: "label" %>
    <%= form.number_field :carbohydrates, class: "input" %>
  </div>

  <div>
    <%= form.label :fats, class: "label" %>
    <%= form.number_field :fats, class: "input" %>
  </div>

  <div class="actions">
    <%= form.submit class:"button is-success"%>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
  <h1 class="is-size-2 has-text-weght-bold mb-3">Editing entry</h1>
  <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do%>
  CaloryLog &ndash; <%= DateTime.now.strftime("%B %e, %Y") %>
<% end %>

<div class="columns mt-6 is-centered>
  <% @entries.each do |entry| %>
    <div class="column is-one-quarter>
      <div class="card">
        <header class="card-header">
        <p class="card-header-title"><%= entry.meal_type %></p>
        </header>
        <div class="card-content">
          <div class="content">
          <p><span class="has-text-weight-bold"><%= entry.calories %></span> calories</p>
          <p><span class="has-text-weight-bold"><%= entry.proteins %></span> grams of protein</p>
          <p><span class="has-text-weight-bold"><%= entry.carbohydrates %></span> grams of carbohydrates</p>
          <p><span class="has-text-weight-bold"><%= entry.fats %></span> grams of fats</p>
          <p class="italic">Logged <%= time_ago_in_words(entry.created_at) %> ago</p>
          </div>
        </div>
        <div class="card-footer">
            <%= link_to 'Show', entry, class: "card-footer-item" %>
            <%= link_to 'Edit', edit_entry_path(entry), class: "card-footer-item" %>
            <%= link_to 'Destroy', entry, method: :delete,date:{confirm: 'Are you sure?' }, class: "card-footer-item" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/entries/new.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
  <h1 class="is-size-2 has-text-weght-bold mb-3">New entry</h1>
  <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/show.html.erb
<div class="columns mt-6 is-centered">
  <div class="column is-one-third">
    <%= render @entry %>
    <div class="columns is-mobile" >
      <div class="columns mt-6" >
        <%= link_to "Edit", edit_entry_path(@entry), class: "button is-gray" %> |
        <%= link_to "Delete", entries_path(@entry), method: :delete, data: { confirm: "Are you sure?" }, class: "button is-gray" %>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaloryLog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.1/css/bulma.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <%= render "shared/header" %>


  <% if notice.present? %>
   <div class="notification is-link is-light"><%= notice %></div>
  <% end %>

  <% if alert.present? %>
   <div class="notification is-danger is-light"><%= alert %></div>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-link is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to root_path, class: "navbar-item" do %>
            <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20">
              <title>location-food</title>
              <path d="M18 11v7a2 2 0 0 1-4 0v-5h-2v3a3 3 0 0 1 3-3H3v11zm4 10a2 2 0 0 1-2-2v1a1 1 0 0 1 2 0v4h1v1a1 1 0 0 1 2 0v4h1V1a1 1 0 0 1 2 0v7a2 2 0 0 1-2 2v8a2 2 0 0 1-4 0v-8z"></path>
            </svg>
            <span class="has-text-weight-bold is-size-4 ml-4">CaloryLog</span>
            <% end %>

          </a>
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
          <span class="navbar-item">
            <%= link_to "Create new entries", new_entry_path, class: "button is-success" %>
          </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        <% if content_for(:title) %>
          <%= yield :title %>
        <% else %>
          CaloryLog
        <% end %>
      </p>
    </div>
  </div>
</section>